AllCops:
  Include:
    - 'lib/**/**.rb'
    - 'test/**/**.rb'
    - 'tasks/**/*.rake'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'gem/**/*'

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 20

Style/RaiseArgs:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/ClassVars:
  Enabled: false

ClassLength:
  Max: 200
