---
project: 'BAID Data'
harvest:
  development: &common_harvest
    base_url: 'nsidc.org/api/dataset/metadata/v2/oai'
    prefix: 'staging'
  integration:
    <<: *common_harvest
    prefix: 'integration'
  test:
    <<: *common_harvest
  staging:
    <<: *common_harvest
log:
  development: &dev_log
    path: './log'
    level: debug
  integration: &common_log
    path: '/var/log'
    level: info
    prefix: 'baid-prototype'
  test:
    path: '/dev'
    api_log: 'null'
    status_log: 'null'
  staging:
    <<: *common_log
  production:
    <<: *common_log
